apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetestest
  namespace: teamuk2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetestest
  template:
    metadata:
      labels:
        app: kubernetestest
    spec:
      containers:
      - name: kubernetestest
        image: vinay4790/testrepo:8
        ports:
        - containerPort: 3000
       
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetestest
  namespace: teamuk2
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30099
  selector:
    app: kubernetestest
